# Generated by Django 5.2.3 on 2025-08-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerdashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='store',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='store',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='store',
            name='transactions',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='managed_stores',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cashier',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='last_login',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
