services:
  - type: web
    name: linemart-frontend
    runtime: node
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://linemart-backend.onrender.com
    region: oregon
    plan: free